Task 4
ADozhyna/angular-mentoring-program pull request #4
Opened 2020-10-15 10:09 UTC by ADozhyna

build-in pipes and directives were implemented
custom pipes and directive were implemented
custom pipes and directive were covered by tests

2020-11-01 18:14 UTC, aamialkovich requested changes

2020-11-01 18:14 UTC, aamialkovich commented on my-app/debug.log
> +[1015/095010.502:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Отличный кандидат на добавление в .gitignore 😃

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/directives/border-color.directive.ts
> +    this.renderer2.setStyle(this.element.nativeElement, 'border-bottom', `5px solid ${color}`);
👍🏻 за renderer

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/directives/border-color.directive.ts
> +      this.borderColor = '#bdee68';
Неплохо было бы вынести эти цвета в константы и дать им осмысленные имена)

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/shared/models/course.model.ts
> +    top: boolean
Я бы все же назвал как в условии - topRated. top немного конфузит и ассоциируется с положением в пространстве :)

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/pipes/order-by.pipe.ts
> +  transform(courses: ICourse[], order: string): unknown {
Ну почему же unknown? Вполне себе ICourse[] :)

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/pipes/order-by.pipe.ts
> +  transform(courses: ICourse[], order: string): unknown {
Этот метод можно упростить, если в качестве order принимать 1, -1 или 0 :)

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +     this.coursesList = this.filterPipe.transform(this.coursesList, this.searchString);
Здесь `coursesList` перетрется пустым массивом, если курс не будет найден. Так что исходный список нужно как-то сохранить :)

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +        top: true
Все правильно 😄

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/directives/border-color.directive.ts
> +    this.borderColor = 'black';
Нужно ли нам на каждый вызов ngOnChanges красить бордер в черный цвет?

2020-11-01 18:14 UTC, aamialkovich commented on my-app/src/app/main/directives/border-color.directive.ts
> +    const date: Date = new Date(this.publicationDate);
Работу с датами можно в отдельный метод вынести)

2020-11-01 18:15 UTC, aamialkovich commented
В основном комментарии минорные. Самое важное подправить функционал по фильтерингу)

2020-11-02 09:01 UTC, ADozhyna commented
Пофиксила)

2020-11-07 17:20 UTC, aamialkovich requested changes

2020-11-07 17:20 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +     if (!this.coursesList.length) {
Если длина равна нулю, то должен отработать первый ngIf (там, где говорится, что нет данных).
В данном случае он не отработает, потому что отрицание нуля даст true и мы вернем исходный массив.

2020-11-30 17:26 UTC, merged