Task 5
ADozhyna/angular-mentoring-program pull request #5
Opened 2020-10-19 07:09 UTC by ADozhyna

Implementation for login service and  courses service was added

2020-11-08 14:43 UTC, aamialkovich requested changes

2020-11-08 14:43 UTC, aamialkovich commented on my-app/src/app/login/components/login-page/login-page.component.html
> +    <form fxLayout="column" fxLayoutAlign="flex-start flex-start" (ngSubmit)="loginService.loginUser()">
Как правило, к заинжектанным сервисам не обращаются из темплейта, а выносят в код класса. Тем более, он помечен как private)
То же самое относится к моделям ниже)

2020-11-08 14:43 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +    this.coursesList = this.coursesService.getList();
На каждой итерации change detection мы будем обновлять список курсов и делать фильтр, что ухудшит перформанс. Лучше было бы оставить это в ngOnChanges)

2020-11-08 14:43 UTC, aamialkovich commented on my-app/src/app/login/components/login-page/login-page.component.ts
> +  constructor(private loginService: AuthService) { }
Обычно приватный инстанс сервиса в классе отличается от имени сервиса только начальной строчной буквой:
`constructor(private authService: AuthService) { }`

2020-11-08 14:43 UTC, aamialkovich commented on my-app/src/app/login/components/login-page/login-page.component.ts
> +  public hide: boolean = true;
Я бы предложил дать более осмысленное имя переменной)
Глаголы обычно используются в названии методов. Поскольку здесь булево значение, то можно написать что-то вроде `isPasswordHidden`)

2020-11-08 14:43 UTC, aamialkovich commented on my-app/src/app/main/components/modal/modal.component.ts
> +    private coursesService: CoursesService) { }
Не думаю, что этот диалог должен зависеть от CoursesService. Возможно, он тебе еще пригодится в дальнейших заданиях для удаления чего-то другого)
Я бы рекомендовал в course-item.component подписаться на закрытие диалога, и, в зависимости от того, был это cancel или close, выполнять логику по удалению)

2020-11-10 17:01 UTC, ADozhyna commented on my-app/src/app/login/components/login-page/login-page.component.html
> +    <form fxLayout="column" fxLayoutAlign="flex-start flex-start" (ngSubmit)="loginService.loginUser()">
+

2020-11-30 17:21 UTC, merged