Task 9
ADozhyna/angular-mentoring-program pull request #9
Opened 2020-12-09 17:23 UTC by ADozhyna

- changed search box behavior
- added debounce
- added displaying user data in header
-  changed logic of auth guard
- added loading block component and service

2020-12-12 13:04 UTC, aamialkovich requested changes

2020-12-12 13:04 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +        filter(value => value.length >= 3),
Будет ли получен список курсов, если пользователь введет 3 символа, а затем их сотрет?

2020-12-12 13:04 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +    this.searchString.valueChanges.subscribe((value) => this.debounceSubject.next(value));
Тоже неплохой вариант, но в задании предлагалось keyup использовать))
Потому что по сути, здесь тебе и сабджект не нужен, ты можешь просто подписаться на valueChanges)

2020-12-12 13:04 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +      ).subscribe(() => {
Не забывай отписываться)
https://medium.com/angular-in-depth/the-best-way-to-unsubscribe-rxjs-observable-in-the-angular-applications-d8f9aa42f6a0

2020-12-12 13:04 UTC, aamialkovich commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +      setInterval(this.spinnerLoaderService.spinnerHide.bind(this.spinnerLoaderService), 2000);
Рекомендую ознакомиться с решением, которое завязано на интерсептор)
https://firstclassjs.com/display-a-loader-on-every-http-request-using-interceptor-in-angular-7/
Да и setInterval каждые две секунды будет вызывать фукнцию, что не есть хорошо. Может, ты имела в виду setTimeout?

2020-12-12 13:08 UTC, aamialkovich commented
Нужно доработать функционал спиннера. На данный момент работает некорректно)

2020-12-13 15:37 UTC, ADozhyna commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +      setInterval(this.spinnerLoaderService.spinnerHide.bind(this.spinnerLoaderService), 2000);
Да setTimeout) перепутала, я его добавила, чтобы  вообще можно было увидеть спиннер, т к  ответ с бекенда приходит очень быстро и его просто не видно.

2020-12-13 16:25 UTC, ADozhyna commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +        filter(value => value.length >= 3),
поправила

2020-12-13 16:26 UTC, ADozhyna commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +      ).subscribe(() => {
+

2020-12-13 16:26 UTC, ADozhyna commented on my-app/src/app/main/components/courses-list/courses-list.component.ts
> +      setInterval(this.spinnerLoaderService.spinnerHide.bind(this.spinnerLoaderService), 2000);
Да, сделала через интерсептор)

2020-12-13 17:03 UTC, aamialkovich approved these changes

2020-12-20 14:06 UTC, merged